//priority: 10
//Create Live 6 Custom Recipes
//Author: Blizzor & RGB

let removeItemsByID = [
  "createfood:minecraft/crafting/crafting/shaped/beef_meatball_stick_2_from_shaped",
  "portalgems:new_gem_overworld",
  "portalgems:new_gem_nether",
  "portalgems:new_gem_end",
  "create_sa:vault_component_recipe",
];
let removeItemsByInput = [
  "create_vibrant_vaults:white_package_frogport",
  "create_vibrant_vaults:orange_package_frogport",
  "create_vibrant_vaults:cyan_package_frogport",
  "create_vibrant_vaults:light_gray_package_frogport",
  "create_vibrant_vaults:gray_package_frogport",
  "create_vibrant_vaults:pink_package_frogport",
  "create_vibrant_vaults:lime_package_frogport",
  "create_vibrant_vaults:yellow_package_frogport",
  "create_vibrant_vaults:light_blue_package_frogport",
  "create_vibrant_vaults:magenta_package_frogport",
  "create_vibrant_vaults:purple_package_frogport",
  "create_vibrant_vaults:blue_package_frogport",
  "create_vibrant_vaults:brown_package_frogport",
  "create_vibrant_vaults:green_package_frogport",
  "create_vibrant_vaults:red_package_frogport",
  "create_vibrant_vaults:black_package_frogport",
];
let removeItemsByOutput = [
  "ars_nouveau:source_gem",
  "createfood:raw_fish_onion_pizza",
  "createfood:fish_onion_pizza",
  "createfood:fish_onion_pizza_slice",
  "createfood:raw_fish_pizza",
  "createfood:fish_pizza",
  "createfood:fish_pizza_slice",
  "createfood:raw_mushroom_pizza",
  "createfood:mushroom_pizza",
  "createfood:mushroom_pizza_slice",
  "createfood:raw_onion_pizza",
  "createfood:onion_pizza",
  "createfood:onion_pizza_slice",
  "createfood:raw_bacon_pizza",
  "createfood:bacon_pizza",
  "createfood:bacon_pizza_slice",
  "createfood:raw_fish_bacon_pizza",
  "createfood:fish_bacon_pizza",
  "createfood:fish_bacon_pizza_slice",
  "createfood:raw_sausage_bacon_pizza",
  "createfood:sausage_bacon_pizza",
  "createfood:sausage_bacon_pizza_slice",
  "createfood:raw_mushroom_bacon_pizza",
  "createfood:mushroom_bacon_pizza",
  "createfood:mushroom_bacon_pizza_slice",
  "createfood:raw_mushroom_fish_pizza",
  "createfood:mushroom_fish_pizza",
  "createfood:mushroom_fish_pizza_slice",
  "createfood:raw_onion_bacon_pizza",
  "createfood:onion_bacon_pizza",
  "createfood:onion_bacon_pizza_slice",
  "createfood:raw_mushroom_onion_pizza",
  "createfood:mushroom_onion_pizza",
  "createfood:mushroom_onion_pizza_slice",
  "createfood:raw_sausage_onion_pizza",
  "createfood:sausage_onion_pizza",
  "createfood:sausage_onion_pizza_slice",
  "createfood:raw_sausage_fish_pizza",
  "createfood:sausage_fish_pizza",
  "createfood:sausage_fish_pizza_slice",
  "createfood:pizza_dough",
  "createfood:pizza_dough_tomato_sauce",
  "createfood:raw_cheese_pizza",
  "createfood:cheese_pizza",
  "createfood:cheese_pizza_slice",
  "createfood:raw_sausage_mushroom_pizza",
  "createfood:sausage_mushroom_pizza",
  "createfood:sausage_mushroom_pizza_slice",
  "createfood:raw_sausage_pizza",
  "createfood:sausage_pizza",
  "createfood:sausage_pizza_slice",
  "farmersdelight:wheat_dough",
  "createfood:beef_meatball",
  "createfood:raw_beef_meatball",
  "create_vibrant_vaults:white_package_frogport",
  "create_vibrant_vaults:orange_package_frogport",
  "create_vibrant_vaults:cyan_package_frogport",
  "create_vibrant_vaults:light_gray_package_frogport",
  "create_vibrant_vaults:gray_package_frogport",
  "create_vibrant_vaults:pink_package_frogport",
  "create_vibrant_vaults:lime_package_frogport",
  "create_vibrant_vaults:yellow_package_frogport",
  "create_vibrant_vaults:light_blue_package_frogport",
  "create_vibrant_vaults:magenta_package_frogport",
  "create_vibrant_vaults:purple_package_frogport",
  "create_vibrant_vaults:blue_package_frogport",
  "create_vibrant_vaults:brown_package_frogport",
  "create_vibrant_vaults:green_package_frogport",
  "create_vibrant_vaults:red_package_frogport",
  "create_vibrant_vaults:black_package_frogport",
];

ServerEvents.recipes((event) => {
  removeItemsByID.forEach((item) => event.remove({ id: item }));
  removeItemsByInput.forEach((item) => event.remove({ input: item }));
  removeItemsByOutput.forEach((item) => event.remove({ output: item }));
});
